name: Learning GitHub Script

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    env:
      COLUMN_ID: 12345678  # replace with your actual GitHub project column ID
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Post a comment on the new issue
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "🎉 You've created this issue comment using GitHub Script!!!"
            })

            // Add the issue to the project column
            await github.rest.projects.createCard({
              column_id: parseInt(process.env.COLUMN_ID),
              content_id: context.payload.issue.id,
              content_type: "Issue"
            })
